### PR TITLE
Add support for self-signed certificates

### PR DESCRIPTION
**Pull request by lin88xu**
Hi, would it be possible for the next release to support self-signed cerificates? Thanks!

### CODE REVIEW

**Comment by tananaev** [comment]
Something is wrong with your PR.

**Comment by lin88xu** [comment]
> Something is wrong with your PR.

Didn't get it, whats wrong?

**Comment by tananaev** [comment]
Why are there 45 changed files? Why does it include my commits?

**Comment by tananaev** [comment]
Wait. Do you understand what a Pull Request is?

**Pull request closed without merging**
